// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Blog Service API
//
//  The Blog Service API defines an HTTP(S) interface.
//  Schemes:
//    http
//  Host: localhost:8080
//  BasePath: /
//  Version: master
//  Contact: Blog Service API<hendros@gmail.com> https://www.melektekno.com/
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
