// Code generated by go-swagger; DO NOT EDIT.

package blog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// BlogCreateHandlerFunc turns a function with the right signature into a blog create handler
type BlogCreateHandlerFunc func(BlogCreateParams) middleware.Responder

// Handle executing the request and returning a response
func (fn BlogCreateHandlerFunc) Handle(params BlogCreateParams) middleware.Responder {
	return fn(params)
}

// BlogCreateHandler interface for that can handle valid blog create params
type BlogCreateHandler interface {
	Handle(BlogCreateParams) middleware.Responder
}

// NewBlogCreate creates a new http.Handler for the blog create operation
func NewBlogCreate(ctx *middleware.Context, handler BlogCreateHandler) *BlogCreate {
	return &BlogCreate{Context: ctx, Handler: handler}
}

/* BlogCreate swagger:route POST /api/v1/blog/create Blog blogCreate

create a new blog

*/
type BlogCreate struct {
	Context *middleware.Context
	Handler BlogCreateHandler
}

func (o *BlogCreate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewBlogCreateParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
