// Code generated by go-swagger; DO NOT EDIT.

package blog

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewBlogGetParams creates a new BlogGetParams object
//
// There are no default values defined in the spec.
func NewBlogGetParams() BlogGetParams {

	return BlogGetParams{}
}

// BlogGetParams contains all the bound params for the blog get operation
// typically these are obtained from a http.Request
//
// swagger:parameters blog.get
type BlogGetParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*blog identifier
	  Required: true
	  In: path
	*/
	BlogID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewBlogGetParams() beforehand.
func (o *BlogGetParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rBlogID, rhkBlogID, _ := route.Params.GetOK("blog_id")
	if err := o.bindBlogID(rBlogID, rhkBlogID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBlogID binds and validates parameter BlogID from path.
func (o *BlogGetParams) bindBlogID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.BlogID = raw

	return nil
}
