// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateBlogRequest create blog request
//
// swagger:model CreateBlogRequest
type CreateBlogRequest struct {

	// blog
	// Required: true
	Blog *Blogs `json:"blog"`
}

// Validate validates this create blog request
func (m *CreateBlogRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBlog(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateBlogRequest) validateBlog(formats strfmt.Registry) error {

	if err := validate.Required("blog", "body", m.Blog); err != nil {
		return err
	}

	if m.Blog != nil {
		if err := m.Blog.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("blog")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("blog")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this create blog request based on the context it is used
func (m *CreateBlogRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBlog(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateBlogRequest) contextValidateBlog(ctx context.Context, formats strfmt.Registry) error {

	if m.Blog != nil {
		if err := m.Blog.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("blog")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("blog")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateBlogRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateBlogRequest) UnmarshalBinary(b []byte) error {
	var res CreateBlogRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
