// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateBlogResponse create blog response
//
// swagger:model CreateBlogResponse
type CreateBlogResponse struct {

	// blog
	// Required: true
	Blog *Blogs `json:"blog"`

	// id
	// Required: true
	ID *string `json:"id"`
}

// Validate validates this create blog response
func (m *CreateBlogResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBlog(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateBlogResponse) validateBlog(formats strfmt.Registry) error {

	if err := validate.Required("blog", "body", m.Blog); err != nil {
		return err
	}

	if m.Blog != nil {
		if err := m.Blog.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("blog")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("blog")
			}
			return err
		}
	}

	return nil
}

func (m *CreateBlogResponse) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this create blog response based on the context it is used
func (m *CreateBlogResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBlog(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateBlogResponse) contextValidateBlog(ctx context.Context, formats strfmt.Registry) error {

	if m.Blog != nil {
		if err := m.Blog.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("blog")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("blog")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateBlogResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateBlogResponse) UnmarshalBinary(b []byte) error {
	var res CreateBlogResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
